### ISSUE TITLE
Hey hey

### ISSUE THREAD

**Issue by imclint21** [shockham/kv_cab#5]
HI @shockham,

Is it possible to communicate by email ? I would like your collaboration for a project :D

It's insane because i've the same idea, and the same name idea of project, and I plan to rebuild it with rust (https://github.com/Type-DB/Type-DB.Core)

💃

**Comment by shockham** [comment]
Hello @clintnetwork, have just replied to the email so going to close the issue here.

**Comment by imclint21** [comment]
Seen ^^
